spring:
    profiles.active: developer
  
---
spring:
    profiles: developer
    main:
        banner-mode: 'off'
    
spring.datasource:
    url: jdbc:mysql://localhost:3306/bluebik_shorturl?useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    test-on-borrow: true
    validation-query: select 1
  
spring.jpa:
    properties:
        hibernate:
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
        ddl-auto: update
        naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    
security:
    basic:
        enabled: false

server:
    port: 8090

logging:
    level:
        org.hibernate:
            SQL: DEBUG
            type: TRACE